baseurl = "https://www.wainejr.com"
title = "Waine, Dev do desempenho"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "pt-br"
defaultContentLanguageInSubdir = false

pagination.pagerSize = 20

uglyURLs = true

pygmentsstyle = "b3"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[build]
useResourceCacheWhen = "fallback"

[params]
author = "Waine Oliveira Jr."
description = "Site do dev do desempenho"
keywords = "blog,developer,personal"
info = "Dev do desempenho"
avatarurl = "images/my-pic.png"
favicon = "android-chrome-192x192.png"
# gravatar = "waine2000@gmail.com"
footercontent = "CTO da Aerosim & Criador de conteúdo."

dateformat = "2, January, 2006"

hideFooter = false
hideCredits = false
hideCopyright = false
since = 2020

# Git Commit in Footer, uncomment the line below to enable it.
commit = "https://github.com/luizdepra/hugo-coder/tree/"

rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorscheme = "auto"

# Hide the toggle button, along with the associated vertical divider
hidecolorschemetoggle = false

# Series see also post count
maxSeeAlsoItems = 5

# Enable Twemoji
enableTwemoji = true

# Custom CSS
custom_css = []

# Custom JS
custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"
#     
# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
#     domain = "wainejr.com"
#     # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#     # serverURL = "analytics.wainejr.com"

[params.meta]
favicon = true
svg = true
faviconVersion = "1"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/wainejr/"
[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 2
url = "https://www.youtube.com/@waine_jr"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/waine_jr/"
[[params.social]]
name = "Discord"
icon = "fa-brands fa-discord fa-2x"
weight = 4
url = "https://discord.gg/NNuzYsNPjV"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/in/waine-junior/"
[[params.social]]
name = "TikTok"
icon = "fa-brands fa-tiktok fa-2x"
weight = 6
url = "https://www.tiktok.com/@waine_jr"
[[params.social]]
name = "E-mail"
icon = "fa fa-envelope fa-2x"
weight = 7
url = "mailto:waine.dev@gmail.com"

[languages.pt-br]
languagename = "Português"

[languages.pt-br.params]
info = [
    "CTO da Aerosim & Criador de conteúdo",
    "[Cursos](/cursos.html) | [Livros](/livros.html) | [Guias](/guias.html)",
]
description = "Site do dev do desempenho"
keywords = "blog,desenvolvedor,pessoal"
footercontent = "CTO da Aerosim & Criador de conteúdo"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "sobre.html"

[[languages.pt-br.menu.main]]
name = "Newsletter"
weight = 2
url = "newsletter.html"

[[languages.pt-br.menu.main]]
name = "Guias"
weight = 3
url = "guias.html"

[[languages.pt-br.menu.main]]
name = "Livros"
weight = 4
url = "livros.html"

[[languages.pt-br.menu.main]]
name = "Cursos"
weight = 5
url = "cursos.html"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 6
url = "contato.html"
